import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { motion } from "framer-motion";

import { api } from "~/utils/api";
import LandingResume from "~/components/LandingResume";
import { Button } from "~/components/ui/button";

export default function Home() {
  return (
    <>
      <Head>
        <title>aire</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex grow">
        <div className="flex max-h-full grow flex-col items-center gap-8 align-middle md:flex-row md:justify-between md:gap-0">
          <motion.div
            initial={{ opacity: 0, y: 40 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            className="flex flex-col gap-4 text-center align-middle font-serif text-5xl font-bold md:text-left mt-8"
          >
            <p className='leading-tight'>Automatically tailor your resume  <span className="bg-gradient-to-r from-black to-slate-400 bg-clip-text text-transparent dark:from-white dark:to-slate-300">
              to each job posting.
            </span></p>

            <div>
              <a href="/auth/signin">
                <Button>Get Started</Button>
              </a>
            </div>
          </motion.div>
          <LandingResume />
        </div>
      </main>
    </>
  );
}